const aesthetics = [
    "70s",
    "80s",
    "90s",
    "Americana",
    "Art Deco",
    "Art Nouveau",
    "African Safari",
    "Baroque",
    "Beach House",
    "Bohemian",
    "Bauhaus",
    "Byzantine",
    "Classic Pizzeria",
    "Classic Traditional",
    "Colonial",
    "Contemporary",
    "Cottagecore",
    "Cosmopolitan",
    "Country",
    "Desert Chic",
    "Eclectic",
    "Enchanted Forest",
    "Futuristic",
    "French Provincial",
    "Gothic",
    "Greek Isle",
    "Hollywood",
    "Industrial",
    "Irish Cottage",
    "Island Paradise",
    "Italian Trattoria",
    "Japanese Minimalist",
    "Jungle Safari",
    "Library or Study",
    "Luxury",
    "Mid-Century Modern",
    "Modern",
    "Minimalist",
    "Modern Gothic",
    "Moroccan",
    "Nautical",
    "Organic",
    "Pacific Northwest",
    "Perpendicular Gothic",
    "Pop Art",
    "Preppy",
    "Rainforest",
    "Renaissance",
    "Retro Diner",
    "Rustic Cabin",
    "Rustic Farmhouse",
    "Scandinavian",
    "Shabby Chic",
    "Southwestern",
    "Southern American",
    "Space Age",
    "Steampunk",
    "Surf Shack",
    "Tribal",
    "Tropical",
    "Tudor Revival",
    "Urban Hipster",
    "Victorian",
    "Victorian Gothic",
    "Vintage Arcade",
    "Wabi-Sabi",
    "Whimsical",
    "y2k",
];
