export const industries = [
  "Agriculture",
  "Automotive",
  "Banking & Finance",
  "Biotechnology",
  "Construction",
  "Consumer Goods",
  "E-commerce",
  "Education",
  "Energy",
  "Entertainment & Media",
  "Fashion & Apparel",
  "Food & Beverage",
  "Healthcare",
  "Hospitality & Travel",
  "Information Technology",
  "Manufacturing",
  "Marketing & Advertising",
  "Pharmaceuticals",
  "Real Estate",
  "Retail",
  "Telecommunications",
  "Transportation & Logistics",
  "Utilities",
];
