export const locationTypes = [
  "Antique Store",
  "Appliance Store",
  "Art Gallery",
  "Art Supply Store",
  "Athletic Wear Store",
  "Auto Parts Store",
  "Baby Store",
  "Bakery",
  "Barbershop",
  "Bedding Store",
  "Bicycle Store",
  "Bookstore",
  "Bridal Store",
  "Camera Store",
  "Outdoor Equipment Store",
  "Candle Store",
  "Candy Store",
  "Ceramics Store",
  "Cheese Shop",
  "Chocolate Shop",
  "Clothing Store",
  "Coffee Shop",
  "Cannabis Dispensary",
  "Convenience Store",
  "Craft Store",
  "Dairy Store",
  "Delicatessen",
  "DIY Store",
  "Donut Shop",
  "Electronics Store",
  "Farmers Market",
  "Fish & Seafood Market",
  "Floral Shop",
  "Fragrance Store",
  "Furniture Store",
  "Fitness Studio",
  "Game Store",
  "Gift Store",
  "Gym",
  "Grocery Store",
  "Handbags Store",
  "Hardware Store",
  "Herbal Store",
  "Hobby Shop",
  "Home Decor Store",
  "Home Goods Store",
  "Ice Cream Shop",
  "Jewelry Store",
  "Kitchenware Store",
  "Leather Goods Store",
  "Lingerie Store",
  "Liquor Store",
  "Maternity Store",
  "Meat Market",
  "Motorcycle Store",
  "Music Store",
  "Musical Instruments Store",
  "Nail Supply Store",
  "Optical Store",
  "Party Supply Store",
  "Pet Store",
  "Pharmacy",
  "Record Store",
  "Restaurant",
  "Shoe Store",
  "Souvenir Store",
  "Stationery Store",
  "Tattoo Parlor",
  "Thrift Store",
  "Toy Store",
  "Video Games Store",
  "Watch & Clock Store",
  "Wellness Spa",
];
