export const locationTypes = [
  "Antique Store",
  "Appliance Store",
  "Art Gallery",
  "Art Supply Store",
  "Athletic Wear Store",
  "Auto Parts Store",
  "Baby Store",
  "Bakery",
  "Barbershop",
  "Bedding Store",
  "Bicycle Store",
  "Bookstore",
  "Bridal Store",
  "Bodega",
  "Camera Store",
  "Outdoor Equipment Store",
  "Candle Store",
  "Candy Store",
  "Ceramics Store",
  "Cheese Shop",
  "Chocolate Shop",
  "Cigar Lounge",
  "Clothing Store",
  "Coffee Shop",
  "Cosmetics Store",
  "Cannabis Dispensary",
  "Convenience Store",
  "Craft Brewery or Distillery",
  "Craft Store",
  "Dairy Store",
  "Delicatessen",
  "DIY Store",
  "Donut Shop",
  "Electronics Repair Shop",
  "Electronics Store",
  "Farmers Market",
  "Fish & Seafood Market",
  "Floral Shop",
  "Fragrance Store",
  "Furniture Store",
  "Fitness Studio",
  "Game Store",
  "Gift Store",
  "Gym",
  "Grocery Store",
  "Handbags Store",
  "Hardware Store",
  "Herbal Store",
  "Hobby Shop",
  "Home Decor Store",
  "Home Goods Store",
  "Ice Cream Shop",
  "Jewelry Store",
  "Kitchenware Store",
  "Laundry or Dry Cleaning",
  "Leather Goods Store",
  "Lingerie Store",
  "Liquor Store",
  "Maternity Store",
  "Meat Market",
  "Motorcycle Store",
  "Music Store",
  "Nail Salon",
  "Optical Store",
  "Party Supply Store",
  "Pawn Shop",
  "Pet Store",
  "Pharmacy",
  "Record Store",
  "Restaurant",
  "Shoe Store",
  "Souvenir Store",
  "Stationery Store",
  "Tattoo Parlor",
  "Thrift Store",
  "Tobacco Shop",
  "Toy Store",
  "Video Games Store",
  "Vintage Shop",
  "Watch & Clock Shop",
  "Wellness Spa",
  "Hair Salon",
  "Adult Store",
];